version: '3'

services:
#    nginx:
#        image: nginx:1.20-alpine
#        ports:
#            - 80:80
#        working_dir: /srv/web
#        volumes:
#            - ./docker-config/nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
#            - ./src:/srv/web
#        depends_on:
#            - php
#            - mysql
#    php:
#        build:
#            context: .
#            dockerfile: php.dockerfile
#        working_dir: /srv/web
#        volumes:
#            - ./src:/srv/web
#            - ${HOME}/.composer:${HOME}/.composer
    mysql:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MARIADB_DATABASE=${DB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
            - MARIADB_USER=${DB_USERNAME}
            - MARIADB_PASSWORD=${DB_PASSWORD}
            - SERVICE_TAGS=dev
            - SERVICE_NAME=mysql
        volumes:
            - ./mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
            # - ./mysql-data:/var/lib/mysql
        ports:
            - 33006:3306
#    node:
#        build:
#            context: .
#            dockerfile: node.dockerfile
#        working_dir: /srv/web
#        volumes:
#            - ./src:/srv/web
#            - ${HOME}/.npm:${HOME}/.npm
#        command: npm run dev
#        ports:
#            - 8080:8080
